---
title: "Daily Reports"

output:
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      bootswatch: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, out.width = "100%")
# knitr::opts_chunk$set(
#   cache = FALSE, cache.lazy = FALSE, autodep = TRUE, warning = FALSE, 
#   message = FALSE, echo = TRUE, dpi = 180,
#   fig.width = 5, fig.height = 3, echo = FALSE
#   )
```

<!--#general comments===========================================================
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# This is [[insert description here - what it does/solve]]
#
# By: mike gaunt, michael.gaunt@wsp.com
#
# README: [[insert brief readme here]]
#-------- [[insert brief readme here]]
#
# *please use 80 character margins
# *please go to https://pkgs.rstudio.com/flexdashboard/articles/layouts.html
# to explore the different layouts available for the flexdashboard framework
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->

<!--#library set-up=============================================================
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#content in this section should be removed if in production - ok for dev -->
```{r}
library(flexdashboard)
library(targets)
library(magrittr)
library(tidyverse)
library(plotly)
library(data.table)
library(DT)
library(lubridate)
library(crosstalk)
```

<!--#source helpers/utilities===================================================
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#content in this section should be removed if in production - ok for dev -->
```{r}
# source(here::here("code/helpers_general.r"))
# source(here::here("code/helpers_plotly.r"))
# source(here::here("code/helpers_DT.r"))
```

<!--#source data================================================================
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#content in this section should be removed if in production - ok for dev 
#area to upload data with and to perform initial munging
#please add test data here so that others may use/unit test these scripts -->


Processing Overview {data-orientation=columns}
================================================================================ 

Column {data-width=600 .tabset .tabset-fade}
--------------------------------------------------------------------------------

### Weekly Counts {#week-agg}
```{r}
print(getwd())
tar_read('tble_accts_type')
```

### Daily Counts {#daily-agg}
```{r}
tar_read('tble_accts_type_wd')
# tble_accts_type_wd
```

Column {data-width=600}
--------------------------------------------------------------------------------
### Processing Date  
```{r fig.height = 2, fig.width=5}

```

### By Trip Date 
```{r fig.height = 2, fig.width=5}

```

Processing Metrics {data-orientation=rows}
================================================================================ 

```{r}

```

Row {data-height=650}
--------------------------------------------------------------------------------

```{r}

```


### Processing Times by Result & Process (agg. monthly)
```{r fig.height = 3, fig.width=4}

```

### Processing Durations per Trip Date:

```{r}

```


Row {data-height=650}
--------------------------------------------------------------------------------

### Raw Data {#raw-box}
```{r fig.height = 2}

```

### By Result Type
```{r}

```

```{r}

```

```{r }

```



