---
title: "ZZ Analysis"
subtitle: "zzzz"
author: "Mg"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
    toc_float:
      collapsed: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  cache = FALSE, cache.lazy = FALSE, autodep = TRUE, warning = FALSE, 
  message = FALSE, echo = TRUE, dpi = 180,
  fig.width = 5, fig.height = 3, echo = FALSE
  )
```

```{js}
function filter_default(){
  document.getElementById("res_created_irr_disp").getElementsByClassName("selectized")[0].selectize.setValue("4. Counts greater than 10,000",false) 
  document.getElementById("res_updatedat").getElementsByClassName("selectized")[0].selectize.setValue("4. Counts greater than 10,000",false) 
}
    
$(document).ready(filter_default);
```

```{r}
library(targets)

library(gauntlet)
library(here)
library(reactable)

```

<!--#source data================================================================
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#content in this section should be removed if in production - ok for dev 
#area to upload data with and to perform initial munging
#please add test data here so that others may use/unit test these scripts -->

```{r cache=FALSE}
# tar_load(data)
# tar_load(model)
tar_load(file_acct_cycle_day_smmry)
tar_load(tble_accts_cycleDay)
tar_load(tble_accts_cycleDay_wd)
```

The following is made directly using the target. 
```{r}
tble_accts_cycleDay
```

The following was made just with the file...
```{r}
# table_accts_cycleDay(
#       file = file_acct_cycle_day_smmry
#       ,id = "data_accts_cycleDay")
```

#sd
```{r}
tble_accts_cycleDay_wd
```




